version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes: 
      - data:/data/db
    env_file: 
      - ./env/mongo.env
    networks:
      - backend-tier
  backendcube:
    build: ./backendcube
    volumes: 
      - logs:/app/logs
      - ./backendcube:/app
      - /app/node_modules
    env_file: 
      - ./env/backend.env
    depends_on:
      - mongodb
    networks:
      - backend-tier
  backendsquare:
    build: ./backendsquare
    volumes: 
      - logs:/app/logs
      - ./backendsquare:/app
      - /app/node_modules
    env_file: 
      - ./env/backend.env
    depends_on:
      - mongodb
    networks:
      - backend-tier
  backendmetric:
    build: ./backendmetric
    volumes: 
      - logs:/app/logs
      - ./backendmetric:/app
      - /app/node_modules
    env_file: 
      - ./env/backend.env
    depends_on:
      - mongodb
    networks:
      - backend-tier
  backendfibonacci:
    build: ./backendfibonacci
    volumes: 
      - logs:/app/logs
      - ./backendfibonacci:/app
      - /app/node_modules
    env_file: 
      - ./env/backend.env
    depends_on:
      - mongodb
    networks:
      - backend-tier
  frontend:
    build: ./frontend
    ports: 
      - '8081:8081'
    volumes: 
      - logs:/app/logs
      - ./frontend:/app
      - /app/node_modules
    depends_on: 
      - backendcube
      - backendmetric
      - backendfibonacci
      - backendsquare
    networks:
      - frontend-tier
      - backend-tier
volumes: 
  data:
  logs:
networks:
  frontend-tier:
  backend-tier:

